server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
spring:
  application:
    name: dream_builder
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.200.100:3306/dream_builder?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Root_123
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 192.168.200.100
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    database: 0
  servlet:
    multipart:
      max-file-size: 50MB

logging:
  pattern:
    console: "[%-20t] %clr(${PID}){magenta} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(%40.40logger{39}){cyan} %clr(:){faint} %m${LOG_EXCEPTION_CONVERSION_WORD:%wEx}%n"
  level:
    com.neu.dreambuilder.mapper: trace

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  auto-dialect: true
  reasonable: true
  support-methods-arguments: true
  page-size-zero: true
  params: count=countSql

mybatis-plus:
  global-config:
    db-config:
      update-strategy: not_null
      logic-not-delete-value: 0

dream-lighter:
  redis:
    lock:
      "lock:"
    donor:
      donation:
        rank: 'donor:donation:rank:'
      project: 'donor:project:'
    kid:
      i: 'kid:'
      award: 'kid:award:'
    hot:
      reply: 'hot:reply:'
    limit:
      id: 'limit:id:'
      ip: 'limit:ip:'
    login-donor: 'login:donor:'
    login-kid: 'login:kid:'
    login-volunteer: 'login:volunteer:'
  sys:
    uuid: 1 # 每台机器配置不同的uuid
    sign-in-duration: P1D
    file-save-path: D:/Empty/